name: Detect changed components
description: ""

inputs:
  all:
    required: false
    default: 'false'
    description: If true, marks all components changed

outputs:
  changed-components:
    value: ${{ steps.changes-by-type.outputs.changed-components }}
    description: A JSON list of changed component names
  changed-component-types:
    value: ${{ steps.changes-by-type.outputs.types }}
    description: Changed component types
  changed-components-by-type:
    value: ${{ steps.changes-by-type.outputs.by-type }}
    description: Changed components by type

runs:
  using: composite
  steps:
    -
      name: Get components info
      id: components-info
      uses: slingshot-pipelines/action-components-info@v1
    -
      id: all-components
      shell: bash
      if: ${{ inputs.all == 'true' }}
      env:
        COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
      run: |
        # List all components

        ALL_COMPONENTS_JSON=$("${{ github.action_path }}/scripts/all-components.sh")

        echo "::debug::All components: $ALL_COMPONENTS_JSON"

        echo "all-components=$ALL_COMPONENTS_JSON >> "$GITHUB_OUTPUT"
    -
      shell: bash
      id: construct-path-filters
      if: ${{ inputs.all != 'true' }}
      env:
        COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
      run: |
        # Construct path filters

        FILTERS=$("${{ github.action_path }}/scripts/path-filters.sh" | yq -o=json -I0 '.')
        echo "::debug::Path filters: $FILTERS"

        echo "path-filters=$FILTERS" >> "$GITHUB_OUTPUT"
    -
      name: Detect module changes
      if: ${{ inputs.all != 'true' }}
      uses: dorny/paths-filter@v4
      id: detect-changes
      with:
        filters: ${{ steps.construct-path-filters.outputs.path-filters }}
    -
      id: changes-by-type
      shell: bash
      env:
        COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
        CHANGES: ${{ steps.all-components.outputs.all-components || steps.detect-changes.outputs.changes }}
      run: |
        # Filter changed components by type

        echo "changed-components=$CHANGES" | tee -a "$GITHUB_OUTPUT"

        CHANGED_COMPONENTS_BY_TYPE=$("${{ github.action_path }}/scripts/changes-by-type.sh")
        echo "changed-components-by-type=$CHANGED_COMPONENTS_BY_TYPE" >> "$GITHUB_OUTPUT"

        CHANGED_TYPES=$(echo "$CHANGED_COMPONENTS_BY_TYPE" | jq -rc 'to_entries | map(.key)')
        echo "changed-component-types=$CHANGED_TYPES" | tee -a "$GITHUB_OUTPUT"
