name: Detect changed components
description: ""

inputs:
  all:
    required: false
    default: 'false'
    description: If true, marks all components changed

outputs:
  changed-components:
    value: ${{ steps.all-components.outputs.all || steps.detect-changes.outputs.changes }}
    description: A JSON list of changed component names
  changed-component-types:
    value: ${{ steps.changes-by-type.outputs.types }}
    description: Changed component types
  changed-components-by-type:
    value: ${{ steps.changes-by-type.outputs.by-type }}
    description: Changed components by type

runs:
  using: composite
  steps:
    -
      name: Get components info
      id: components-info
      uses: slingshot-pipelines/action-components-info@v0
    -
      id: all-components
      shell: bash
      if: ${{ inputs.all == 'true' }}
      env:
        COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
      run: |
        # List all components
        echo "::group::List all components"
        ALL_COMPONENTS_JSON=$("${{ github.action_path }}/scripts/all-components.sh")
        echo "$ALL_COMPONENTS_JSON"
        echo "::endgroup::"

        echo "all=$ALL_COMPONENTS_JSON >> "$GITHUB_OUTPUT"
    -
      shell: bash
      id: construct-path-filters
      if: ${{ inputs.all != 'true' }}
      env:
        COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
      run: |
        # Construct path filters
        echo "::group::Construct path filters"
        FILTERS=$("${{ github.action_path }}/scripts/path-filters.sh" | yq -o=json -I0 '.')
        echo "$FILTERS"
        echo "::endgroup::"

        echo "filters=$FILTERS" >> "$GITHUB_OUTPUT"
    -
      name: Detect module changes
      if: ${{ inputs.all != 'true' }}
      uses: dorny/paths-filter@v4
      id: detect-changes
      with:
        filters: ${{ steps.construct-path-filters.outputs.filters }}
    -
      id: changes-by-type
      shell: bash
      env:
        COMPONENTS_INFO: ${{ steps.components-info.outputs.info }}
        CHANGES: ${{ steps.all-components.outputs.all || steps.detect-changes.outputs.changes }}
      run: |
        # Filter changed components by type
        echo "::group::Filter changes by type"

        CHANGED_BY_TYPE=$("${{ github.action_path }}/scripts/changes-by-type.sh")
        echo "$CHANGED_BY_TYPE" | jq '.'

        echo "::endgroup::"

        TYPES=$(echo "$CHANGED_BY_TYPE" | jq -rc 'to_entries | map(.key)')

        echo "types=$TYPES" >> "$GITHUB_OUTPUT"
        echo "by-type=$CHANGED_BY_TYPE" >> "$GITHUB_OUTPUT"
